### ISSUE TITLE
LOC link is broken

### ISSUE THREAD

**Issue by JTatum95** [projectblacklight/blacklight_cql#1]
I get a 403 error whenever I try to access http://www.loc.gov/standards/sru/cql/ 

Since this was the provided resource for understanding cql syntax that is rather important so I thought I would let you know.

**Comment by jrochkind** [comment]
That URL is currently resolving for me. Maybe it was temporarily down?  Is it currently working for you?

**Comment by JTatum95** [comment]
Yeah it looks like it was a temporary outage. Closing now. Thanks!
